# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Kuntai Du
tagline:          'Kuntai Du'
description:      'A Ph.D. Student in UChicago, a math lover and music lover.'
baseurl:          /

author:
  name:           'Kuntai Du'

paginate:         5

# Custom vars
version:          2.1.0

gem: [jekyll-paginate, jekyll-gist]

github:
  repo:           https://github.com/KuntaiDu

theme: minimal
